### ISSUE TITLE
Remote download

### ISSUE THREAD

**Issue by gtbu** [kalcaddle/kodfile#1]
I installed kodfile successful under xammp php7.1 and can upload local - but not remote like

https://www.typesettercms.com/Plugins/17_Simple_Blog?cmd=download

Success - but the file is 0Byte   Is there a solution ?

**Comment by kalcaddle** [comment]
beacuse this url is not a real download link.

it's download by the page and run with encode js.
request:
![image](https://user-images.githubusercontent.com/3761968/54799028-4d779a00-4c96-11e9-8e86-2e7c057256a6.png)


return header：
![image](https://user-images.githubusercontent.com/3761968/54799070-7e57cf00-4c96-11e9-9a80-4b229984ab57.png)
